name: Release to Maven Central

on:
  workflow_dispatch: # Permette l'esecuzione manuale

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Prepare GPG environment
        run: |
          mkdir -p ~/.gnupg
          chmod 700 ~/.gnupg
          echo "use-agent" >> ~/.gnupg/gpg.conf
          echo "pinentry-mode loopback" >> ~/.gnupg/gpg.conf
        env:
          GPG_TTY: $(tty)

      - name: Import GPG key
        run: |
          echo "${{ secrets.GPG_PRIVATE_KEY }}" > private.key
          gpg --batch --yes --pinentry-mode loopback --import private.key
          gpg --list-secret-keys --keyid-format LONG

      - name: Check Maven settings
        run: |
          cat .github/maven-settings.xml

      - name: Build and deploy
        run: |
          mvn clean deploy -DskipTests -P release --settings .github/maven-settings.xml
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_TOKEN_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_TOKEN_PASSWORD }}
