name: Run Integration Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  integration-tests:
    name: Run Integration Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Decode secrets.properties file
        env:
          STRIPE_API_KEY: ${{ secrets.STRIPE_API_KEY }}
        run: echo "$STRIPE_API_KEY" | base64 -d > ./secrets.properties

      - name: Set up environment variables (optional)
        run: |
          # Assuming the decoded secrets.properties has the STRIPE_API_KEY variable
          export STRIPE_API_KEY=$(grep 'stripe.apiKey' ./secrets.properties | cut -d'=' -f2)
          echo "STRIPE_API_KEY=$STRIPE_API_KEY" >> $GITHUB_ENV

      - name: Build and run tests (including integration tests)
        run: mvn clean verify -Dstripe.apiKey=${{ env.STRIPE_API_KEY }} --settings .github/maven-settings.xml
